import frappe

# for compatibility
null = None

currency_list = {
	"doc_type": "Currency Exchange",
	"data": [
		{
			"date": frappe.utils.nowdate(), 
			"doctype": "Currency Exchange", 
			"exchange_rate": 48.0, 
			"from_currency": "USD", 
			"name": "USD-DOP", 
			"to_currency": "DOP"
		}, 
		{
			"date": frappe.utils.nowdate(), 
			"doctype": "Currency Exchange", 
			"exchange_rate": 48.0, 
			"from_currency": "DOP", 
			"name": "DOP-USD", 
			"to_currency": "USD"
		}
	]
}

custom_field_list = {
	"doc_type": "Custom Field",
	"data" : [
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": "eval:doc.vehicle_insurance", 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Payment Entry", 
			"fieldname": "insurance", 
			"fieldtype": "Currency", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "column_break_21", 
			"label": "Insurance", 
			"name": "Payment Entry-insurance", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "2", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "amount", 
			"fieldtype": "Currency", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "policy_no", 
			"label": "Amount", 
			"name": "Vehicle-amount", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "2", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": "", 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "renew", 
			"fieldtype": "Button", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "amount", 
			"label": "Renew", 
			"name": "Vehicle-renew", 
			"no_copy": 0, 
			"options": "", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "rate", 
			"fieldtype": "Percent", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "end_date", 
			"label": "Rate", 
			"name": "Vehicle-rate", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "cuotas_seguro", 
			"fieldtype": "Section Break", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "financiamiento", 
			"label": "Cuotas Seguro", 
			"name": "Vehicle-cuotas_seguro", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "cuotas", 
			"fieldtype": "Table", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "cuotas_seguro", 
			"label": "Cuotas", 
			"name": "Vehicle-cuotas", 
			"no_copy": 0, 
			"options": "Insurance Repayment Schedule", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		},
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Customer", 
			"fieldname": "cedula", 
			"fieldtype": "Data", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "customer_name", 
			"label": "Cedula", 
			"name": "Customer-cedula", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 1, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 1, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Customer", 
			"fieldname": "referencias", 
			"fieldtype": "Section Break", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "disabled", 
			"label": "References Section", 
			"name": "Customer-referencias", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Customer", 
			"fieldname": "references", 
			"fieldtype": "Table", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "referencias", 
			"label": "References", 
			"name": "Customer-references", 
			"no_copy": 0, 
			"options": "Referencia", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 1, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "loan", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "remark", 
			"label": "Loan", 
			"name": "Journal Entry-loan", 
			"no_copy": 0, 
			"options": "", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 1, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 1, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Payment Entry", 
			"fieldname": "loan", 
			"fieldtype": "Link", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "mora", 
			"label": "Loan", 
			"name": "Payment Entry-loan", 
			"no_copy": 1, 
			"options": "Loan", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 1, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "year", 
			"fieldtype": "Int", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 1, 
			"in_standard_filter": 0, 
			"insert_after": "model", 
			"label": "Year", 
			"name": "Vehicle-year", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": "eval:doc.mora", 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Payment Entry", 
			"fieldname": "mora", 
			"fieldtype": "Data", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "paid_amount", 
			"label": "Mora", 
			"name": "Payment Entry-mora", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": "0", 
			"depends_on": "eval:doc.loan", 
			"description": "Numero del Pagare", 
			"doctype": "Custom Field", 
			"dt": "Payment Entry", 
			"fieldname": "pagare", 
			"fieldtype": "Int", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "column_break_5", 
			"label": "Pagare No", 
			"name": "Payment Entry-pagare", 
			"no_copy": 1, 
			"options": "", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 1, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		},
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": "1", 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Vehicle", 
			"fieldname": "financiamiento", 
			"fieldtype": "Check", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "rate", 
			"label": "Es Financiamiento", 
			"name": "Vehicle-financiamiento", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 1, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": "", 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Payment Entry", 
			"fieldname": "es_un_pagare", 
			"fieldtype": "Check", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "mode_of_payment", 
			"label": "Es un pagare?", 
			"name": "Payment Entry-es_un_pagare", 
			"no_copy": 1, 
			"options": "", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 1, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": "0", 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "es_un_pagare", 
			"fieldtype": "Check", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "amended_from", 
			"label": "Es un pagare", 
			"name": "Journal Entry-es_un_pagare", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Purchase Invoice", 
			"fieldname": "poliza_de_seguro", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "recurring_print_format", 
			"label": "Poliza de Seguro", 
			"name": "Purchase Invoice-poliza_de_seguro", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 1, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "pagare", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "es_un_pagare", 
			"label": "Pagare", 
			"name": "Journal Entry-pagare", 
			"no_copy": 0, 
			"options": "", 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 1, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "insurance", 
			"fieldtype": "Data", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "pagare", 
			"label": "Insurance", 
			"name": "Journal Entry-insurance", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 1, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry Account", 
			"fieldname": "repayment_field", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "against_account", 
			"label": "", 
			"name": "Journal Entry Account-repayment_field", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 1, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 1, 
			"report_hide": 1, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "dutty_amount", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "insurance", 
			"label": "", 
			"name": "Journal Entry-dutty_amount", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "partially_paid", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "dutty_amount", 
			"label": "", 
			"name": "Journal Entry-partially_paid", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "amount_paid", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "partially_paid", 
			"label": "", 
			"name": "Journal Entry-amount_paid", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "fine_discount", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "amount_paid", 
			"label": "", 
			"name": "Journal Entry-fine_discount", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "loan_amount", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "fine_discount", 
			"label": "", 
			"name": "Journal Entry-loan_amount", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "insurance_amount", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "loan_amount", 
			"label": "", 
			"name": "Journal Entry-insurance_amount", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "pending_amount", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "insurance_amount", 
			"label": "", 
			"name": "Journal Entry-pending_amount", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "fine", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "pending_amount", 
			"label": "", 
			"name": "Journal Entry-fine", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "mode_of_payment", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "fine", 
			"label": "", 
			"name": "Journal Entry-mode_of_payment", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "repayment_no", 
			"fieldtype": "Data", 
			"hidden": 1, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "mode_of_payment", 
			"label": "", 
			"name": "Journal Entry-repayment_no", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}, 
		{
			"allow_on_submit": 0, 
			"collapsible": 0, 
			"collapsible_depends_on": null, 
			"default": null, 
			"depends_on": null, 
			"description": null, 
			"doctype": "Custom Field", 
			"dt": "Journal Entry", 
			"fieldname": "currency", 
			"fieldtype": "Data", 
			"hidden": 0, 
			"ignore_user_permissions": 0, 
			"ignore_xss_filter": 0, 
			"in_filter": 0, 
			"in_list_view": 0, 
			"in_standard_filter": 0, 
			"insert_after": "repayment_no", 
			"label": "", 
			"name": "Journal Entry-currency", 
			"no_copy": 0, 
			"options": null, 
			"permlevel": 0, 
			"precision": "", 
			"print_hide": 0, 
			"print_hide_if_no_value": 0, 
			"print_width": null, 
			"read_only": 0, 
			"report_hide": 0, 
			"reqd": 0, 
			"search_index": 0, 
			"unique": 0, 
			"width": null
		}
	]
}

custom_script_list = {
	"doc_type": "Custom Script",
	"data": [
		{
			"doctype": "Custom Script", 
			"dt": "Vehicle", 
			"name": "Vehicle-Client", 
			"script": "frappe.ui.form.on('Vehicle', {\n    validate: function(frm) {\n        cuotas = frm.doc.cuotas\n        if (cuotas && cuotas.length > 0) {\n            total_insurance = 0\n\n            cuotas.forEach(function(row) {\n                total_insurance += row.amount\n            })\n\n            frappe.call({\n                method: \"fm.utilities.add_insurance_to_loan\",\n                args: {\n                    \"chasis_no\": frm.doc.license_plate,\n                    \"total_insurance\": total_insurance\n                },\n                callback: function(response) {\n                    var name = response.message\n\n                    frappe.show_alert(\n                        repl(\"Loan %(loan)s was updated\", {\n                            \"loan\": name\n                        }),\n                    10)\n                }\n            })\n        }\n    },\n    renew: function(frm) {\n        if ( !frm.doc.insurance_company )\n            frappe.throw(\"Debe ingresar el nombre de la aseguradora\")\n\n        if ( !frm.doc.policy_no )\n            frappe.throw(\"Debe ingresar el numero de poliza del cliente\")\n\n        if (frm.doc.financiamiento) {\n            if (frm.doc.amount > 0) {\n                amount = Math.ceil(frm.doc.amount / 3)\n                var today = frappe.datetime.get_today()\n                date = frappe.datetime.add_months(today, 1)\n\n                frm.clear_table(\"cuotas\")\n\n                for (i = 0; i < 3; i++) {\n                    frm.add_child(\"cuotas\", { \"date\": date, \"amount\": amount, \"status\": \"PENDING\" })\n\n                    date = frappe.datetime.add_months(date, 1)\n                }\n\n                refresh_field(\"cuotas\")\n                frm.save()\n            } else {\n                frappe.msgprint(\"Si opta por el financiamiento el monto de la poliza debe ser mayor que cero\")\n            }\n        } else {\n            frm.set_value(\"amount\", 0)\n        }\n    },\n    validate: function(frm) {\n        // create a new Array from the history\n        var new_history = Array.from(frappe.route_history)\n\n        // then reversed the new history array\n        var reversed_history = new_history.reverse()\n\n        // not found flag to stop the bucle\n        var not_found = true\n\n        // iterate the array to find the last Loan visited\n        $.each(reversed_history, function(idx, value) {\n            \n            // see if there is a Loan that was visited in this\n            // section. if found it the redirects the browser to\n            // asumming that the user came from that Loan\n            if (not_found && \"Form\" == value[0] && \"Loan\" == value[1]) {\n\n                // give a timeout before switching the location\n                setTimeout(function() {\n                    // set the route to the latest opened Loan\n                    frappe.set_route(value)\n                }, 1500)\n\n                // set the flag to false to finish\n                not_found = false\n            }\n        })\n    }\n})", 
			"script_type": "Client"
		}, 
		{
			"doctype": "Custom Script", 
			"dt": "Translation", 
			"name": "Translation-Client", 
			"script": "frappe.ui.form.on(\"Translation\", {\n    refresh: function(frm) {\n        if(frm.doc.__islocal) return\n        frm.add_custom_button(__(\"Duplicate\"), function(event){\n            frm.doc.source_name = \"\"\n            frm.doc.target_name = \"\"\n            frm.copy_doc()\n        })\n    }\n})\n", 
			"script_type": "Client"
		}, 
		{
			"doctype": "Custom Script", 
			"dt": "ToDo", 
			"name": "ToDo-Client", 
			"script": "frappe.ui.form.on(\"ToDo\", {\n\tonload: function(frm){\n  \t\tfrm.set_df_property(\"reference_name\", \"read_only\", frm.doc.reference_type==\"Loan\")\n\t}\n})", 
			"script_type": "Client"
		}, 
		{
			"doctype": "Custom Script", 
			"dt": "Journal Entry", 
			"name": "Journal Entry-Client", 
			"script": "frappe.ui.form.on(\"Journal Entry\", {\n    refresh: function(frm) {\n        var callback = function(response) {\n            if (frm.doc.__islocal || !response.message) \n                return 0 // exit code is zero\n\n            var list = response.message\n            var cur_route, prev_route, next_route\n            var index = 0, prev_index = 0, next_index = 0\n\n            for ( ; index < list.length; index++) {\n                prev_index = index - 1 < 0 ? 0 : index - 1\n                next_index = index + 1 >= list.length ? list.length - 1 : index + 1\n\n                if (frm.doc.name == list[index].name) {\n                    prev_route = list[prev_index].name\n                    next_route = list[next_index].name\n                    cur_route = list[index].name\n\n                    break\n                }\n            }\n\n            var route_next = function(res) {\n                set_emp_route(next_route)\n            }\n            var route_prev = function(res) {\n                set_emp_route(prev_route)\n            }\n            var set_emp_route = function(docname) {\n                frappe.set_route([\"Form\", frm.doctype, docname])\n            }\n\n            if (prev_route != cur_route) frm.add_custom_button(\"<< Prev\", route_prev)\n\n            if (next_route != cur_route) frm.add_custom_button(\"Next >>\", route_next)\n        }\n\n        frappe.call({\n            \"method\": \"frappe.client.get_list\",\n            \"args\": {\n                \"doctype\": frm.doctype,\n                \"limit_page_lentgh\": 0,\n                \"filters\": {\n                    \"loan\": frm.doc.loan,\n                    \"es_un_pagare\": frm.doc.es_un_pagare\n                }\n            },\n            \"callback\": callback\n        })\n    },\n    on_submit: function(frm) {\n        // create a new Array from the history\n        var new_history = Array.from(frappe.route_history)\n\n        // then reversed the new history array\n        var reversed_history = new_history.reverse()\n\n        // not found flag to stop the bucle\n        var not_found = true\n\n        // iterate the array to find the last Loan visited\n        $.each(reversed_history, function(idx, value) {\n\n            // see if there is a Loan that was visited in this\n            // section. if found it the redirects the browser to\n            // asumming that the user came from that Loan\n            if (not_found && \"Form\" == value[0] && \"Loan\" == value[1]) {\n\n                // give a timeout before switching the location\n                setTimeout(function() {\n                    // set the route to the latest opened Loan\n                    // frappe.set_route(value)\n                }, 1500)\n\n                // set the flag to false to finish\n                not_found = false\n            }\n        })\n    }\n})", 
			"script_type": "Client"
		}, 
		{
			"doctype": "Custom Script", 
			"dt": "Payment Entry", 
			"name": "Payment Entry-Client", 
			"script": "frappe.ui.form.on(\"Payment Entry\", {\n    on_submit: function(frm) {\n        // create a new Array from the history\n        var new_history = Array.from(frappe.route_history)\n\n        // then reversed the new history array\n        var reversed_history = new_history.reverse()\n\n        // not found flag to stop the bucle\n        var not_found = true\n\n        // iterate the array to find the last Loan visited\n        $.each(reversed_history, function(idx, value) {\n            \n            // see if there is a Loan that was visited in this\n            // section. if found it the redirects the browser to\n            // asumming that the user came from that Loan\n            if (not_found && \"Form\" == value[0] && \"Loan\" == value[1]) {\n\n                // give a timeout before switching the location\n                setTimeout(function() {\n                    // set the route to the latest opened Loan\n                    frappe.set_route(value)\n                }, 1500)\n\n                // set the flag to false to finish\n                not_found = false\n            }\n        })\n    },\n    es_un_pagare: function(frm){\n\n        // validate is the checkbox is checked first\n        if ( !frm.doc.es_un_pagare ){\n\n            // let's clear the pagare\n            frm.set_value(\"pagare\", 0)\n\n            // let's clear the loan\n            frm.set_value(\"loan\", undefined)\n\n            return 0 // exit is zero\n        }\n            \n        var callback = function(data){\n            frm.set_value(\"loan\", data.loan)\n\n            var _method = \"fm.api.next_repayment\"\n\n            var _args = {\n                \"loan\": frm.doc.loan\n            }\n\n            var _callback = function(response){\n\n                // set the response the repayment variable\n                var repayment = response.message\n\n                // set the index value to the pagare number\n                frm.set_value(\"pagare\", repayment.idx)\n            }\n\n            frappe.call({ \"method\": _method, \"args\": _args, \"callback\": _callback })\n        }\n\n        // link field to Loan List\n        var link_field = { \"label\": \"Prestamo\", \"fieldname\": \"loan\", \"fieldtype\": \"Link\", \"options\": \"Loan\" }\n\n        if ( !frm.doc.prompt ){\n\n            // let's show the prompt\n            frm.doc.prompt = frappe.prompt(link_field, callback, \"Seleccione el Prestamo\", \"Continuar\")\n        } else {\n            // let's just make it visible\n            var p = frm.doc.prompt\n\n            p.show()\n        }\n    }\n})", 
			"script_type": "Client"
		}, 
		{
			"doctype": "Custom Script", 
			"dt": "Purchase Invoice", 
			"name": "Purchase Invoice-Client", 
			"script": "frappe.ui.form.on(\"Purchase Invoice\", {\n    onload_post_render: function(frm) {\n        if ( !frm.doc.docstatus && frm.doc.poliza_de_seguro){\n            frm.set_intro(\"Valide este documento para confirmar que se ha finalizado con la compra!\")\n        }\n    },\n    on_submit: function(frm) {\n        // create a new Array from the history\n        var new_history = Array.from(frappe.route_history)\n\n        // then reversed the new history array\n        var reversed_history = new_history.reverse()\n\n        // not found flag to stop the bucle\n        var not_found = true\n\n        // iterate the array to find the last Loan visited\n        $.each(reversed_history, function(idx, value) {\n\n            // see if there is a Loan that was visited in this\n            // section. if found it then redirect the browser to\n            // asumming that the user came from that Loan\n            if (not_found && \"Form\" == value[0] && \"Loan\" == value[1]) {\n\n                // give a timeout before switching the location\n                setTimeout(function() {\n                    // set the route to the latest opened Loan\n                    //frappe.set_route(value)\n                }, 1500)\n\n                // set the flag to false to finish\n                not_found = false\n            }\n        })\n    }\n});", 
			"script_type": "Client"
		}
	]
}